# Generated by Django 3.2.4 on 2021-06-07 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_de_compra', models.IntegerField()),
                ('fecha', models.DateTimeField()),
                ('numero_de_factura', models.IntegerField()),
            ],
        ),
    ]
