# Generated by Django 3.2.4 on 2021-06-07 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flores', '0003_auto_20210606_2222'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario_de_flores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('tipo', models.CharField(max_length=64)),
                ('nit', models.CharField(max_length=64)),
                ('temporada', models.CharField(max_length=64)),
                ('ocasion', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='cliente',
            name='correo',
            field=models.EmailField(max_length=64),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(max_length=64),
        ),
    ]
