# Generated by Django 3.2.4 on 2021-06-07 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flores', '0004_auto_20210607_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='numero_de_factura',
            field=models.IntegerField(),
        ),
    ]
