# Generated by Django 3.2.4 on 2021-06-07 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flores', '0005_alter_compra_numero_de_factura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='numero_de_factura',
            field=models.FloatField(),
        ),
    ]
