# Generated by Django 3.2.4 on 2021-06-07 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flores', '0006_alter_compra_numero_de_factura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='flores_en_descuento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flores.inventario_de_flores'),
        ),
    ]
